



  postgresql:
    container_name: "postgresqlpostgis"
    image: "postgis/postgis"
    ports: 
      - "5433:5432"
    volumes:
       - db_persdata:/var/lib/postgrespers
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bdtuto



volumes:
  db_persdata : {}
